
export enum TypographyVariants {
    Heading1 = 'heading1',
    Heading2 = 'heading2',
    Heading3 = 'heading3',
    Heading4 = 'heading4',
    Heading5 = 'heading5',
    Heading6 = 'heading6',
    Paragraph = 'paragraph',
    Span = 'span',
    // Anchor = 'anchor',
    // Strong = 'strong',
    // Emphasis = 'emphasis',
    // Abbreviation = 'abbreviation',
    // Blockquote = 'blockquote',
    // Code = 'code',
    // Preformatted = 'preformatted',
    // List = 'list',
    // OrderedList = 'orderedList',
    // ListItem = 'listItem',
    // DefinitionTerm = 'definitionTerm',
    // DefinitionDescription = 'definitionDescription',
    // Marked = 'marked',
    // Time = 'time',
    // Variable = 'variable',
    // Small = 'small',
    // Subscript = 'subscript',
    // Superscript = 'superscript',
    // Deleted = 'deleted',
    // Inserted = 'inserted',
    // KeyboardInput = 'keyboardinput',
    // Sample = 'sample',
    // Cite = 'cite',
    // Q = 'q',
    // Address = 'address',
}
export const TypographyTags = new Map([
    [TypographyVariants.Heading1, 'h1'],
    [TypographyVariants.Heading2, 'h2'],
    [TypographyVariants.Heading3, 'h3'],
    [TypographyVariants.Heading4, 'h4'],
    [TypographyVariants.Heading5, 'h5'],
    [TypographyVariants.Heading6, 'h6'],
    [TypographyVariants.Paragraph, 'p'],
    [TypographyVariants.Span, 'span'],
    // [TypographyVariants.Anchor, 'a'],
    // [TypographyVariants.Strong, 'strong'],
    // [TypographyVariants.Emphasis, 'em'],
    // [TypographyVariants.Abbreviation, 'abbr'],
    // [TypographyVariants.Blockquote, 'blockquote'],
    // [TypographyVariants.Code, 'code'],
    // [TypographyVariants.Preformatted, 'pre'],
    // [TypographyVariants.List, 'ul'],
    // [TypographyVariants.OrderedList, 'ol'],
    // [TypographyVariants.ListItem, 'li'],
    // [TypographyVariants.DefinitionTerm, 'dt'],
    // [TypographyVariants.DefinitionDescription, 'dd'],
    // [TypographyVariants.Marked, 'mark'],
    // [TypographyVariants.Time, 'time'],
    // [TypographyVariants.Variable, 'var'],
    // [TypographyVariants.Small, 'small'],
    // [TypographyVariants.Subscript, 'sub'],
    // [TypographyVariants.Superscript, 'sup'],
    // [TypographyVariants.Deleted, 'del'],
    // [TypographyVariants.Inserted, 'ins'],
    // [TypographyVariants.KeyboardInput, 'kbd'],
    // [TypographyVariants.Sample, 'samp'],
    // [TypographyVariants.Cite, 'cite'],
    // [TypographyVariants.Q, 'q'],
    // [TypographyVariants.Address, 'address'],
])
export enum TextAlignmentOptions {
    Left = 'left',
    Right = 'right',
    Center = 'center',
    Inherit = 'inherit',
}
export enum TextTransformOptions {
    None = 'none',
    Lowercase = 'lowercase',
    Uppercase = 'uppercase',
    Capitalize = 'capitalize'
}
export enum FontWeight {
    Thin = 'thin',
    ExtraLight = 'extralight',
    Light = 'light',
    Normal = 'normal',
    Medium = 'medium',
    SemiBold = 'semibold',
    Bold = 'bold',
    ExtraBold = 'extrabold',
    Black = 'black',
}
export enum FontSizes {
    ExtraSmall = 'extrasmall',
    Small = 'small',
    Normal = 'normal',
    Medium = 'medium',
    Large = 'large',
    ExtraLarge = 'extralarge',
}
export type ElementClassList = { [key: string]: boolean };