/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { FontSizes, FontWeight, TextAlignmentOptions, TextTransformOptions, TypographyVariants } from "./models/sds-typography";
export { FontSizes, FontWeight, TextAlignmentOptions, TextTransformOptions, TypographyVariants } from "./models/sds-typography";
export namespace Components {
    interface SdsButton {
    }
    interface SdsTypography {
        "align"?: TextAlignmentOptions;
        "case"?: TextTransformOptions;
        "size"?: FontSizes;
        "variant": TypographyVariants;
        "weight"?: FontWeight;
    }
}
declare global {
    interface HTMLSdsButtonElement extends Components.SdsButton, HTMLStencilElement {
    }
    var HTMLSdsButtonElement: {
        prototype: HTMLSdsButtonElement;
        new (): HTMLSdsButtonElement;
    };
    interface HTMLSdsTypographyElement extends Components.SdsTypography, HTMLStencilElement {
    }
    var HTMLSdsTypographyElement: {
        prototype: HTMLSdsTypographyElement;
        new (): HTMLSdsTypographyElement;
    };
    interface HTMLElementTagNameMap {
        "sds-button": HTMLSdsButtonElement;
        "sds-typography": HTMLSdsTypographyElement;
    }
}
declare namespace LocalJSX {
    interface SdsButton {
    }
    interface SdsTypography {
        "align"?: TextAlignmentOptions;
        "case"?: TextTransformOptions;
        "size"?: FontSizes;
        "variant"?: TypographyVariants;
        "weight"?: FontWeight;
    }
    interface IntrinsicElements {
        "sds-button": SdsButton;
        "sds-typography": SdsTypography;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "sds-button": LocalJSX.SdsButton & JSXBase.HTMLAttributes<HTMLSdsButtonElement>;
            "sds-typography": LocalJSX.SdsTypography & JSXBase.HTMLAttributes<HTMLSdsTypographyElement>;
        }
    }
}
